version: '3.9'
services:
  cloudcine-db:
    image: postgres:15
    container_name: cloudcine-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  cloudcine-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cloudcine-app
    command: "./bin/dev"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - cloudcine-db
    stdin_open: true
    
volumes:
  db-data:
