services:
  cloudcine-db:
    image: postgres:15
    container_name: cloudcine-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cloudcine-network

  # cloudcine-redis:
  #   image: redis:alpine
  #   command: ["redis-server", "--appendonly", "yes"]
  #   volumes:
  #     - redis-data:/data
  #   ports:
  #     - "9001:6379"
  #   networks:
  #     - cloudcine-network

  cloudcine-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cloudcine-app
    command: "./bin/dev"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/app/assets/builds
    ports:
      - "3000:3000"
    depends_on:
      - cloudcine-db
    stdin_open: true
    networks:
      - cloudcine-network
    
volumes:
  db-data:
  redis-data: {}

networks:
  cloudcine-network:
    driver: bridge